# Generated by Django 5.2.1 on 2025-05-23 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTareas', '0002_remove_tarea_completada_tarea_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En progreso'), ('hecha', 'Hecha'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20),
        ),
    ]
